accounts/urls.py
from django.urls import path

from .views import UserProfileView, EditProfile, RemoveFollower, AddFollower, ListFollowers

app_name="accounts"

urlpatterns = [
    path('<username>/', UserProfileView, name="profile"),
    path('profile/edit', EditProfile, name="edit-profile"), 

    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
	path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers/',ListFollowers.as_view(), name='followers-list'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('accounts.urls', namespace='users')),
    path('social/', include('social.urls', namespace='social')),
    path('', HomeView.as_view(), name='home'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/sidebars/left/items.html
{% load static %}

<ul class="p-4">
    <li>
        <a href="{% url 'users:profile' user.username %}" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
            <img src="{{user.profile.picture.url}}" alt="Profile picture" class="w-10 h-10 rounded-full">
            <span class="font-semibold">{{user.username}}</span>
        </a>
    </li>
    <li>
        <a href="#" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-group text-gray-500'></i>
            <span class="font-semibold">Friends</span>
        </a>
    </li>
    
    {% comment %} <li>
        <a href="#" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
            <span class="w-10 h-10 rounded-full grid place-items-center bg-gray-300 dark:bg-dark-second">
                <i class='bx bx-chevron-down'></i>
            </span>
            <span class="font-semibold">See more</span>
        </a>
    </li> {% endcomment %}
    <li class="border-b border-gray-200 dark:border-dark-third mt-6"></li>
</ul>

templates/components/sidebars/left/sidebar.html
{% load static %}

{% include 'components/sidebars/left/items.html' %}

{% include 'components/footer.html' %}